### PR TITLE
Adding Helm chart to install VAST CSI

### PR DESCRIPTION
**Pull request by aw1cks**
Hello!

I have written this Helm chart to install the VAST CSI into my clusters. I thought this may be useful to others as Helm is often a preferred method of installation, with lots of tooling support.

I'm not sure if this is something that you would accept. Please let me know if you have any queries or concerns and I am happy to address them. If there are any contribution guidelines that I may need to follow, please do point me towards them.

### CODE REVIEW

**Comment by koreno** [comment]
Hello @aw1cks, thank you so much for your contribution!
Can you provide a command-line example for reference?

**Comment by aw1cks** [comment]
Absolutely!

Below is a bare-bones example of installation:

```shell
$ cat values.yaml
---

vastEndpoint: https://my.vast.example.com
vastUser: admin
vastPassword: supersecurepassword
vastVipPool: main
$ # Print out the YAML manifests that will be applied
$ helm template -f values.yaml ./deployment/helm/vastcsi
$ # Install as helm release named 'vast-csi-installation'
$ helm install -f values.yaml vast-csi-installation ./deployment/helm/vastcsi
```

**Comment by koreno** [comment]
@aw1cks - thanks for your contribution! I expect this will be formally released in the upcoming version.

**Comment by aw1cks** [comment]
Thanks for getting this reviewed and merged promptly!

**Pull request merged**
